### ISSUE TITLE
Update G Suite to Google Workspace

### ISSUE THREAD

**Issue by St3ph-fr** [limhenry/gde-badge-generator#3]
Hi,

Is it possible to update the "G Suite" option in Category name to "Google Workspace".

Thank you

**Comment by limhenry** [comment]
Updated. You should see "Google Workspace" in the list now.

By the way, the "dropdown" is actually editable. You can write whatever thing you like there 😉

![image](https://user-images.githubusercontent.com/4544770/190452981-196369c9-1fd1-4777-b231-e022fdc9fdfa.png)

**Comment by St3ph-fr** [comment]
Thanks that is perfect ;-)

Good job for the application.

Stéphane
